const lessons=[
["Деректер қоры дегеніміз не және ол не үшін қажет?","🗄️","Деректер қорының не екенін және қолданбалардың оны не үшін пайдаланатынын үйреніңіз.","Деректер қоры ақпаратты реттейді, сондықтан компьютер оны сақтап, тауып және жаңарта алады."],
["Кестелер әлемі: өрістер мен жазбалар","📊","Жолдар, бағандар, өрістер және жазбалармен танысыңыз.","Кесте өзара байланысты ақпаратты түсінікті құрылымда сақтайды."],
["Ақпаратты сұрыптау және сүзу","🔎","Қажетті ақпаратты жылдам табуды үйреніңіз.","Сұрыптау реттілікті өзгертеді, ал сүзу шартқа сәйкес жазбаларды ғана көрсетеді."],
["Деректер түрлері: мәтін, сандар және күндер","🔤","Компьютерге сақталатын ақпараттың түрін анықтауды үйреніңіз.","Мәтін, сандар, күндер және логикалық мәндердің әрқайсысының өз қызметі бар."],
["Бастапқы кілт дегеніміз не?","🔑","Кестедегі бірегей идентификаторды табыңыз.","Бастапқы кілт әрбір жазбаны бірегей түрде анықтайды."],
["Реляциялық деректер қорлары және кестелер арасындағы байланыстар","🔗","Кестелерді байланыстырып, олардың арасындағы байланыстарды зерттеңіз.","Кестелер 1:1, 1:N және N:M сияқты байланыстар арқылы біріктіріледі."],
["Сұраныстар: компьютермен сөйлесу","💬","Деректер қорына сұрақ қойып, пайдалы нәтиже алыңыз.","Сұраныс деректер қорынан белгілі бір шарттарға сәйкес жазбаларды табуды сұрайды."],
["Пішіндер: интерактивті дерек енгізу","📝","Ақпарат енгізуге ыңғайлы пішіндерді пайдаланыңыз.","Пішіндер адамдарға деректерді енгізуді және өзгертуді жеңілдетеді."],
["Есептер: ақпаратты ұсыну","📈","Сақталған деректерді пайдалы есептер мен диаграммаларға айналдырыңыз.","Есептер деректер қорындағы ақпаратты түсінікті түрде қорытындылайды."],
["Деректер қауіпсіздігі және құпиялылық","🛡️","Деректерді жоғалудан, ұрланудан және рұқсатсыз қолжетімділіктен қорғаңыз.","Құпиясөздер, шифрлау, рұқсаттар және резервтік көшірмелер ақпаратты қорғауға көмектеседі."]
];
const achievements=[
["⭐","Бірінші миссия","1-сабақты аяқтаңыз",1],
["🚀","Зерттеуші","3 сабақты аяқтаңыз",3],
["💻","Код жаңадан бастаушысы","5 сабақты аяқтаңыз",5],
["🛡️","Кибер-қорғаушы","10-сабақты аяқтаңыз",10],
["🌟","Деректер қорының шебері","Барлық 10 сабақты аяқтаңыз",10]
];
let state=JSON.parse(localStorage.getItem("codequest"))||{аяқталды:[],scores:{},xp:0,avatar:"🤖"};
function save(){localStorage.setItem("codequest",JSON.stringify(state))}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function level(){return Math.floor(state.xp/200)+1}
function render(){
applyTheme();
const app=document.getElementById("app");
app.innerHTML=`<div class="app"><div class="stars"></div>${nav()}<main id="main"></main><div class="footer">CodeQuest • Үйрен. Зертте. Шеш. 🚀</div>${aiChatMarkup()}</div>`;
route(location.hash||"#home");
}

function getTheme(){return localStorage.getItem("codequest-theme")||"dark"}
function applyTheme(){document.body.classList.toggle("light-theme",getTheme()==="light")}
function toggleTheme(){localStorage.setItem("codequest-theme",getTheme()==="light"?"dark":"light");applyTheme();render()}
function nav(){
return `<nav class="nav"><a class="logo" href="#home"><span class="logo-b">🚀</span>CodeQuest</a><div class="navlinks">
<button type="button" data-nav="#home" onclick="location.hash='#home'">Home</button><button type="button" data-nav="#lessons" onclick="location.hash='#lessons'">Сабақтар</button><button type="button" data-nav="#progress" onclick="location.hash='#progress'">Менің прогресім</button><button type="button" data-nav="#achievements" onclick="location.hash='#achievements'">Жетістіктер</button><button type="button" data-nav="#about" onclick="location.hash='#about'">Біз туралы</button></div>
<div class="userbox"><button class="theme-toggle" onclick="toggleTheme()" aria-label="Тақырыпты ауыстыру" title="Тақырыпты ауыстыру">${getTheme()==="light"?"🌙":"☀️"}</button><span class="xp">⭐ ${state.xp} XP</span><span class="avatar" onclick="location.hash='#profile'">${state.avatar}</span></div></nav>`;
}
function route(hash){
document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===hash));
const main=document.getElementById("main");
if(hash==="#lessons")main.innerHTML=mapPage();
else if(hash==="#progress")main.innerHTML=progressPage();
else if(hash==="#achievements")main.innerHTML=achievementPage();
else if(hash==="#about")main.innerHTML=aboutPage();
else if(hash.startsWith("#lesson-"))main.innerHTML=lessonPage(+hash.split("-")[1]);
else if(hash==="#profile")main.innerHTML=profilePage();
else main.innerHTML=homePage();
bind();
}
function homePage(){
let next=state.аяқталды.length<10?state.аяқталды.length:9, p=Math.round(state.аяқталды.length/10*100);
return `<section class="page"><div class="hero"><div><div class="eyebrow">Техно-зерттеуші, қош келдің!</div><h1>Информатика <span class="gradient">шытырманы</span></h1><p>Деректер қорлары әлемін аралап, тапсырмаларды орындаңыз, XP жинаңыз және біздің AI-көмекшіміз әрі CodeQuest маскоты — Қасқырмен бірге жаңа миссияларды ашыңыз.</p><div class="hero-actions"><button class="cta" onclick="location.hash='#lesson-${next}'">${state.аяқталды.length?'Миссияны жалғастыру':'Оқуды бастау'} 🚀</button><button class="ghost" onclick="location.hash='#lessons'">Картаны зерттеу</button></div></div><div class="mascot-wrap wolf-hero"><div class="planet"></div><div class="bubble">Келесі миссияға дайынсыз ба? Мен сізге көмектесемін! 🐺</div><img class="wolf-hero-img" src="wolf-mascot-transparent.png" alt="CodeQuest AI-көмекшісі және маскоты — Қасқыр"></div></div>
<div class="stats"><div class="card stat"><span class="muted">Ағымдағы XP</span><b>${state.xp}</b><span class="muted">Деңгей ${level()} · Техно-зерттеуші</span></div><div class="card stat"><span class="muted">Сабақтар</span><b>${state.аяқталды.length}/10</b><span class="muted">${p}% complete</span></div><div class="card stat"><span class="muted">Орташа ұпай</span><b>${average()}%</b><span class="muted">Зерттеуді жалғастырыңыз!</span></div><div class="card stat"><span class="muted">Жетістіктер</span><b>${earnedЖетістіктер()}</b><span class="muted">ашылған белгілер</span></div></div>
<div class="section-title"><h2>Шытырманды жалғастырыңыз</h2></div><div class="card mission-card"><div><span class="badge">МИССИЯ ${String(next+1).padStart(2,"0")}</span><h2>${lessons[next][0]}</h2><p class="muted">${lessons[next][2]}</p><div class="progress"><i style="width:${state.аяқталды.includes(next)?100:35}%"></i></div></div><button class="cta" onclick="location.hash='#lesson-${next}'">${state.аяқталды.includes(next)?'Қайта өту':'Жалғастыру'} →</button></div></section>`;
}
function mapPage(){
return `<section class="page"><div class="section-title"><div><div class="eyebrow">Оқу шытырманы</div><h2>CodeQuest ғаламын зерттеңіз</h2><p class="muted">Келесі әлемге жол ашу үшін миссияны аяқтаңыз.</p></div></div><div class="map"><div class="path"><svg viewBox="0 0 1000 850" preserveAspectRatio="none"><path d="M80 80 C420 40, 300 180, 700 220 S350 400, 760 450 S350 650, 800 760" fill="none" stroke="#65eaff55" stroke-width="7" stroke-dasharray="14 18"/></svg></div>${lessons.map((l,i)=>node(l,i)).join("")}</div></section>`;
}
function node(l,i){
const done=state.аяқталды.includes(i), available=i===0||state.аяқталды.includes(i-1);
let pos=[["12%","10%"],["42%","18%"],["75%","26%"],["28%","38%"],["60%","44%"],["84%","56%"],["38%","62%"],["15%","74%"],["60%","80%"],["85%","91%"]][i];
return `<div class="lesson-node ${done?'done':available?'available':'locked'}" style="left:${pos[0]};top:${pos[1]}" onclick="${available?`location.hash='#lesson-${i}'`:''}"><div class="node">${done?'✓':available?l[1]:'🔒'}</div><div class="node-title">Сабақ ${i+1}</div><div class="muted">${esc(l[0])}</div>${done?`<div class="node-score">${state.scores[i]||0}%</div>`:''}</div>`;
}
function lessonPage(i){
if(i<0||i>9)return homePage();
const l=lessons[i],done=state.аяқталды.includes(i);
return `<section class="page lesson-page"><button class="ghost back" onclick="location.hash='#lessons'">← Шытырман картасына оралу</button><div class="lesson-head"><div><span class="badge">МИССИЯ ${String(i+1).padStart(2,"0")} ${done?'· COMPLETED':''}</span><h1>${l[1]} ${esc(l[0])}</h1><p class="muted">${l[2]}</p></div><div class="card"><b>⭐ +100 XP</b><br><span class="muted">Миссияны аяқтаңыз</span></div></div>
<div class="mission-tabs"><button class="tab active" data-tab="learn">1 · Үйрену</button><button class="tab" data-tab="watch">2 · Көру</button><button class="tab" data-tab="practice">3 · Практика</button><button class="tab" data-tab="test">4 · Қорытынды тест</button></div>
<div id="lessonContent" class="lesson-content">${learnContent(i)}</div></section>`;
}
function learnContent(i){
const l=lessons[i];
return `<div class="info-grid"><div class="card"><span class="eyebrow">Миссия нұсқаулығы</span><h2>Қош келдің, зерттеуші! 🚀</h2><p>${l[3]}</p><p>Бұл ұғымды шынайы цифрлық әлемнің бір бөлігі ретінде елестетіңіз. Мысалдарды зерттеп, кейін практикалық миссияда біліміңізді тексеріңіз.</p></div><div class="card"><h2>Byte-тың кеңесі 💡</h2><p>«Күрделі компьютерлік ұғымдарды шағын бөліктерге бөліңіз. Бөліктерін түсінсеңіз, бүкіл жүйені түсіну әлдеқайда оңай!»</p></div></div><div class="card interactive"><h2>Жылдам тексеру</h2><p>Қай әрекет жақсырақ үйренуге көмектеседі?</p><button class="answer" onclick="quick(this,true)">Мысалды зерттеп, оны өз сөзіңізбен түсіндіріңіз</button><button class="answer" onclick="quick(this,false)">Барлығын өткізіп, кездейсоқ жауап беріңіз</button><div id="feedback"></div></div>`;
}
function watchContent(i){
const watched=JSON.parse(localStorage.getItem("codequest-video-watched")||"[]").includes(i);
return `<div class="video-lesson card"><div class="video-title"><div><span class="eyebrow">Видео сабақ</span><h2>Миссия видеосы — ${esc(lessons[i][0])}</h2><p class="muted">Қысқа бейне-сабақты көріп, негізгі ұғымдарды бекітіңіз.</p></div><span class="video-duration">▶ 20 сек</span></div><div class="video-frame"><video controls preload="metadata" playsinline poster="lesson-${i+1}.mp4"><source src="lesson-${i+1}.mp4" type="video/mp4">Браузеріңіз видео ойнатуды қолдамайды.</video></div><div class="video-actions"><span class="muted">${watched?'✅ Видео қаралды':'🎬 Видеоны соңына дейін көріп шығыңыз'}</span><button class="cta" onclick="markVideoWatched(${i})">${watched?'Қайта қарау':'Көрілді деп белгілеу +10 XP'}</button></div></div>`
}
function markVideoWatched(i){let a=JSON.parse(localStorage.getItem("codequest-video-watched")||"[]");if(!a.includes(i)){a.push(i);localStorage.setItem("codequest-video-watched",JSON.stringify(a));state.xp+=10;save();toast("Видео аяқталды! +10 XP");}else toast("Бұл видео бұрын қаралған");switchTab("watch",i)}
function practiceContent(i){const q=["A database is mainly used to…","A row in a table is called a…","Filtering helps you…","Which value is a Boolean?","A primary key should be…","1:N means…","A query can…","A form is useful for…","A report can contain…","Which helps protect personal data?"][i];const opts=[["Ақпаратты ұйымдастыру","Сурет салу","Батареяны зарядтау"],["Жазба","Өріс","Құпиясөз"],["Сәйкес жазбаларды көрсету","Интернетті өшіру","Компьютерді өшіру"],["Ақиқат","2026","Алиса"],["Бірегей","Кездейсоқ","Қайталанатын"],["Бірден-көпке","Байланыс жоқ","Тек бір ұяшық"],["Сәйкес деректерді табу","Дауыстап сөйлесу","Құрылғыны жөндеу"],["Деректерді енгізу","Электрді өзгерту","Пернетақта жасау"],["Диаграммалар мен қорытындылар","Тек құпиясөздер","Тек ойындар"],["Күшті құпиясөздер","Құпиясөздерді бөлісу","Резервтік көшірмелерді елемеу"]][i];return `<div class="card interactive"><span class="eyebrow">Практикалық тапсырма</span><h2>${q}</h2>${opts.map((o,n)=>`<button class="answer" onclick="practice(this,${n===0})">${o}</button>`).join("")}<div id="feedback"></div></div>`}
function testContent(i){return `<div class="card interactive"><span class="eyebrow">Қорытынды тест</span><h2>Миссияны тексеруге дайынсыз ба? 🧠</h2><p>Қорытынды сұраққа жауап беріңіз. Дұрыс жауап миссияны аяқтап, XP береді.</p><h3>${["Деректер қорын не үшін қолданамыз?","Жазба дегеніміз не?","Сүзу не істейді?","Қайсысы сан?","Бастапқы кілт не үшін қажет?","Байланыс нені біріктіреді?","Сұраныс нені қайтарады?","Пішінді не үшін қолданамыз?","Есеп нені көрсете алады?","Қайсысы қауіпсіздікке пайдалы әдет?"][i]}</h3>${["Ақпаратты ұйымдастыру және табу","Байланысты мәндерден тұратын жол","Тек сәйкес жазбалар","42","Жазбаны бірегей анықтау","Байланысты кестелер","Сәйкес жазбалар","Деректерді оңай енгізу","Диаграммалар мен қорытындылар","Күшті бірегей құпиясөз қолдану"][i]?`<button class="answer" onclick="finishTest(${i})">Choose the correct answer ✓</button>`:''}<div id="feedback"></div></div>`}
function switchTab(tab,i){
document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));
document.getElementById("lessonContent").innerHTML=tab==="learn"?learnContent(i):tab==="watch"?watchContent(i):tab==="practice"?practiceContent(i):testContent(i);
}
function quick(el,ok){el.classList.add(ok?"correct":"wrong");document.getElementById("feedback").innerHTML=`<p>${ok?'🌟 Керемет! Практикаға дайынсыз.':'💡 Дәл емес. Басқа жауапты байқап көріңіз!'}</p>`}
function practice(el,ok){el.classList.add(ok?"correct":"wrong");document.getElementById("feedback").innerHTML=`<p>${ok?'⭐ Керемет жұмыс! +10 XP':'💡 Not quite! Try again.'}</p>`}
function finishTest(i){if(!state.аяқталды.includes(i)){state.аяқталды.push(i);state.scores[i]=85+Math.floor(Math.random()*16);state.xp+=100;save();celebrate();}document.getElementById("lessonContent").innerHTML=`<div class="card result"><div class="big">+100 XP</div><h1>Миссия аяқталды! 🚀</h1><p>Сіздің ұпайыңыз <b>${state.scores[i]}%</b> бұл миссия бойынша.</p><p>${i<9?'Келесі миссия енді ашылды!':'Сіз бүкіл CodeQuest шытырманын аяқтадыңыз! 🌟'}</p><button class="cta" onclick="location.hash='${i<9?'#lesson-'+(i+1):'#achievements'}'">${i<9?'Шытырманды жалғастыру →':'Жетістіктерді көру →'}</button></div>`;toast("Миссия аяқталды! +100 XP")}
function progressPage(){return `<section class="page"><div class="section-title"><div><div class="eyebrow">Сіздің жолыңыз</div><h2>Менің прогресім</h2></div></div><div class="stats"><div class="card stat"><span class="muted">Ағымдағы XP</span><b>${state.xp}</b></div><div class="card stat"><span class="muted">Деңгей</span><b>${level()}</b></div><div class="card stat"><span class="muted">Аяқталды</span><b>${state.аяқталды.length}/10</b></div><div class="card stat"><span class="muted">Average</span><b>${average()}%</b></div></div><div class="section-title"><h2>Миссия ұпайлары</h2></div><div class="score-grid">${lessons.map((l,i)=>`<div class="card"><b>Сабақ ${i+1}</b><h3>${l[0]}</h3><div class="progress"><i style="width:${state.scores[i]||0}%"></i></div><p class="muted">${state.scores[i]?state.scores[i]+'%':'Әлі аяқталмаған'}</p></div>`).join("")}</div></section>`}
function achievementPage(){return `<section class="page"><div class="section-title"><div><div class="eyebrow">Сыйлықтар</div><h2>Жетістіктер</h2><p class="muted">Ғаламды зерттей отырып, белгілер жинаңыз.</p></div></div><div class="achievement-grid">${achievements.map(a=>`<div class="card achievement ${earned(a[3],a[1])?'':'locked'}"><div class="icon">${a[0]}</div><h3>${a[1]}</h3><p class="muted">${a[2]}</p><b>${earned(a[3],a[1])?'АШЫЛДЫ':'ҚҰЛЫПТАУЛЫ'}</b></div>`).join("")}</div></section>`}
function aboutPage(){return `<section class="page about-page"><div class="section-title"><div><div class="eyebrow">CodeQuest командасы</div><h2>Біз туралы</h2><p class="muted">Информатиканы қызықты, заманауи және ұлттық нақышпен үйренуге арналған білім беру жобасы.</p></div></div><div class="about-grid"><div class="card wolf-card"><div class="wolf-art real-wolf"><img src="wolf-mascot-transparent.png" alt="CodeQuest AI-көмекшісі және маскоты Қасқыр"></div><div><span class="badge">CODEQUEST AI-КӨМЕКШІСІ • МАСКОТ</span><h2>Қасқыр — біздің ақылды серігіміз 🐺</h2><p>Қасқыр — CodeQuest жобасының AI-көмекшісі әрі негізгі маскоты. Ол оқушыға миссиялар барысында бағыт береді, мотивация береді және информатиканы қызықты зерттеуге көмектеседі.</p><p>Оның қазақы ұлттық киімі мен ою-өрнектері жобаның заманауи технологияны ұлттық мәдениетпен үйлестіру идеясын көрсетеді.</p></div></div><div class="card"><span class="eyebrow">Біздің мақсатымыз</span><h2>Оқу — шытырманға айналсын! 🚀</h2><p>CodeQuest 5–6 сынып оқушыларына информатика тақырыптарын ойын, практика, видео сабақтар және тесттер арқылы меңгеруге көмектеседі.</p><div class="about-points"><div>🎯 <b>10 миссия</b><span>Деректер қоры әлемін кезең-кезеңімен зерттеу</span></div><div>⭐ <b>XP және жетістіктер</b><span>Әр қадам үшін мотивация мен марапат</span></div><div>🇰🇿 <b>Қазақша контент</b><span>Оқушыға түсінікті әрі жақын тіл</span></div></div></div></div><div class="section-title team-title"><div><div class="eyebrow">Жобаны жасаушылар</div><h2>Біздің команда</h2></div></div><div class="team-grid"><div class="card team-card"><img class="team-avatar team-photo" src="dtlnaz-avatar.jpeg" alt="Исмагулова Дтльназ"><h3>Исмагулова Дтльназ</h3><p class="muted">ҚазҰПУ · 3 курс</p><span class="badge">CodeQuest командасы</span></div><div class="card team-card"><img class="team-avatar team-photo" src="sabina-avatar.jpeg" alt="Бақытқызы Сабина"><h3>Бақытқызы Сабина</h3><p class="muted">ҚазҰПУ · 3 курс</p><span class="badge">CodeQuest командасы</span></div></div></section>`}
function profilePage(){return `<section class="page"><div class="section-title"><div><div class="eyebrow">Зерттеуші профилі</div><h2>Менің профилім</h2></div></div><div class="profile"><div class="card profile-card"><div class="profile-avatar">${state.avatar}</div><h2>Техно-зерттеуші</h2><p class="muted">Деңгей ${level()}</p><button class="cta" onclick="changeAvatar()">Аватарды өзгерту</button></div><div class="card"><h2>Жол статистикасы</h2><div class="bar-row"><div class="label"><b>Келесі деңгейге дейінгі XP</b><span>${state.xp%200}/200</span></div><div class="progress"><i style="width:${(state.xp%200)/2}%"></i></div></div><div class="bar-row"><div class="label"><b>Сабақтар</b><span>${state.аяқталды.length}/10</span></div><div class="progress"><i style="width:${state.аяқталды.length*10}%"></i></div></div><p>Орташа ұпай: <b>${average()}%</b></p><p>Жетістіктер: <b>${earnedЖетістіктер()}</b></p></div></div></section>`}
function average(){let a=Object.values(state.scores);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0}
function earned(n,name){if(name==="Бірінші миссия")return state.аяқталды.length>=1;if(name==="Зерттеуші")return state.аяқталды.length>=3;if(name==="Код жаңадан бастаушысы")return state.аяқталды.length>=5;if(name==="Кибер-қорғаушы")return state.аяқталды.includes(9);return state.аяқталды.length>=10}
function earnedЖетістіктер(){return achievements.filter(a=>earned(a[3],a[1])).length}
function toast(msg){let x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function celebrate(){let c=document.createElement("div");c.className="confetti";for(let i=0;i<55;i++){let s=document.createElement("span");s.style.left=Math.random()*100+"%";s.style.top=(-10-Math.random()*20)+"%";s.style.animationDelay=Math.random()*.5+"s";s.style.transform=`rotate(${Math.random()*360}deg)`;c.appendChild(s)}document.body.appendChild(c);setTimeout(()=>c.remove(),1800)}
function changeAvatar(){const a=["🤖","👨‍🚀","👩‍🚀","🧑‍💻","🦊","🐼","🐱","👽"];state.avatar=a[(a.indexOf(state.avatar)+1)%a.length];save();render()}
function aiChatMarkup(){return `<div id="aiChat" class="ai-chat"><button class="ai-fab" onclick="toggleAIChat()" aria-label="AI көмекшісін ашу"><img src="wolf-mascot-transparent.png" alt="Қасқыр"> <span>AI</span></button><div class="ai-panel" id="aiPanel"><div class="ai-head"><div class="ai-head-left"><img src="wolf-mascot-transparent.png" alt="Қасқыр"><div><b>Қасқыр</b><small>CodeQuest AI-көмекшісі</small></div></div><button class="ai-close" onclick="toggleAIChat()">×</button></div><div class="ai-messages" id="aiMessages"><div class="ai-msg bot">Сәлем! 🐺 Мен Қасқырмын. Сабақ, практика, тест немесе CodeQuest туралы сұрақ қой — бірге шешеміз!</div><div class="ai-quick"><button onclick="askAI('1-сабақты түсіндір')">1-сабақты түсіндір</button><button onclick="askAI('Маған оқу жоспарын айт')">Оқу жоспары</button><button onclick="askAI('XP қалай жинаймын?')">XP қалай жинаймын?</button></div></div><div class="ai-input"><input id="aiInput" placeholder="Сұрағыңды жаз..." onkeydown="if(event.key==='Enter')sendAIMessage()"><button onclick="sendAIMessage()">➤</button></div></div></div>`}
function toggleAIChat(){document.getElementById('aiPanel')?.classList.toggle('open');setTimeout(()=>document.getElementById('aiInput')?.focus(),50)}
function askAI(q){const input=document.getElementById('aiInput');if(input){input.value=q;sendAIMessage()}}
function aiReply(q){const x=q.toLowerCase();if(x.includes('1-сабақ')||x.includes('деректер қоры'))return 'Деректер қоры — ақпаратты реттеп сақтауға арналған жүйе. Мысалы, мектеп оқушыларының аты-жөні мен бағаларын бір жерден сақтап, тез табуға болады. 🗄️';if(x.includes('xp')||x.includes('ұпай'))return 'XP сабақтарды оқу, практика орындау және қорытынды тесттерді аяқтау арқылы жиналады. Әр миссияны аяқтасаң, жаңа сабақтарға жол ашылады! ⭐';if(x.includes('жоспар')||x.includes('оқу'))return 'CodeQuest-та 10 миссия бар: алдымен Үйрену, кейін Видео сабақ, Практика және соңында Қорытынды тест. Сабақтарды ретімен аяқтаған дұрыс. 🚀';if(x.includes('тест'))return 'Тестте жауапты асықпай таңда. Қате болса, түсіндірмені қарап, қайта байқап көр. Мен саған тақырыпты түсіндіре аламын. 💡';if(x.includes('практика'))return 'Практикада тақырып бойынша шағын тапсырма орындайсың. Дұрыс жауап білімді бекітуге көмектеседі. 🧩';if(x.includes('волк')||x.includes('қасқыр'))return 'Мен — Қасқыр, CodeQuest-тің AI-көмекшісі әрі маскоты! 🐺 Қазақы ою-өрнекпен безендірілген киімім жобаның ұлттық стилін көрсетеді.';if(x.includes('codequest')||x.includes('біз туралы')||x.includes('команда'))return 'CodeQuest — 5–6 сынып оқушыларына арналған информатика оқу жобасы. Жобаны Исмагулова Дтльназ және Бақытқызы Сабина, ҚазҰПУ 3 курс студенттері әзірледі. 🇰🇿';if(x.includes('сабақ')||x.includes('lesson'))return 'Қазір 10 сабақ бар. «Сабақтар» бөлімінен картаға өтіп, ашылған миссияны таңда. 🗺️';return 'Қызық сұрақ! Мен саған информатика, деректер қоры, сабақтар, практика, тесттер және CodeQuest туралы көмектесе аламын. Сұрағыңды сәл нақтылап көрші. 🐺'}
function sendAIMessage(){const input=document.getElementById('aiInput'),box=document.getElementById('aiMessages');if(!input||!box)return;const q=input.value.trim();if(!q)return;box.insertAdjacentHTML('beforeend',`<div class="ai-msg user">${esc(q)}</div>`);input.value='';setTimeout(()=>{box.insertAdjacentHTML('beforeend',`<div class="ai-msg bot">${aiReply(q)}</div>`);box.scrollTop=box.scrollHeight},180);box.scrollTop=box.scrollHeight}

function bind(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>location.hash=b.dataset.nav);document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab,+location.hash.split("-")[1]));}
window.addEventListener("hashchange",()=>route(location.hash));
render();
